apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: acme-issuer
spec:
  acme:
    email: hpo.sareno@gmail.com
    # Staging
    #server: https://acme-staging-v02.api.letsencrypt.org/directory
    # Production
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: acme-issuer
    solvers:
    - http01:
        ingress:
          ingressClassName: traefik
