apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader-rb
subjects:
- kind: ServiceAccount
  name: pod-reader
roleRef:
  kind: ClusterRole
  name: pod-reader
  apiGroup: ""
