apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
  namespace: company-xyz
  labels:
    app: whoami
spec:
  replicas: 3
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      name: whoami
      labels:
        app: whoami
        os: linux
    spec:
      containers:
      - name: whoami
        image: containous/whoami
        ports:
        - name: http
          containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: whoami-svc
  namespace: company-xyz
spec:
  type: NodePort
  selector:
    app: whoami
  ports:
  - port: 80
    targetPort: http
    nodePort: 30101
