apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: company-abc
spec: {}
status: {}
---

apiVersion: v1
kind: Namespace
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: company-xyz
spec: {}
status: {}
