apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: company-abc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      dist: alpine
  template:
    metadata:
      name: nginx
      namespace: company-abc
      labels:
        app: nginx
        dist: alpine
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - name: http
          containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: company-abc
spec:
  selector:
    app: nginx
    dist: alpine
  type: NodePort
  ports:
  - port: 80
    targetPort: http
    nodePort: 30100
