apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgres
  name: postgres
  namespace: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
      namespace: postgres
    spec:
      containers:
      - image: postgres:15.3
        name: postgres
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: pgdata
          mountPath: /var/lib/postgresql/data
        env:
        - name: POSTGRES_PASSWORD
          # WARNING: this is unsafe, must be retriived somewhere else e.g., secrets
          value: myUnsafeHardCodedPassword
        - name: POSTGRES_DB
          value: mydb
      volumes:
      - name: pgdata
        persistentVolumeClaim:
          claimName: postgres-pvc
