apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-secrets
subjects:
- kind: ServiceAccount
  name: secret-reader # name is case sensitive
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: secret-reader
  apiGroup: ""
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
subjects:
- kind: ServiceAccount
  name: pod-reader # name is case sensitive
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: pod-reader
  apiGroup: ""
