apiVersion: v1
kind: Pod
metadata:
  name: pod-can-read
spec:
  containers:
  - name: pod-can-read
    image: nginx
    volumeMounts:
    - name: the-secrets
      mountPath: "/opt/secrets"
  volumes:
  - name: the-secrets
    secret:
      secretName: i-am-a-secret
      optional: true
---

apiVersion: v1
kind: Pod
metadata:
  name: pod-cannot-read
spec:
  containers:
  - name: pod-cannot-read
    image: nginx
    volumeMounts:
    - name: the-secrets
      mountPath: "/opt/secrets"
  volumes:
  - name: the-secrets
    secret:
      secretName: i-am-a-secret
      optional: true
